name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionando mensagens de log
        run: |
         echo "::debug:: Mensagem de Log Debug"
         echo "::warning:: Mensagem de Warning"
         echo "::notice:: Mensagem de Notice"
         echo "::error:: Mensagem de Error executado por ${{ github.actor }}"